indent_style = "Visual"
use_small_heuristics = "Max"
comment_width = 100
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
error_on_line_overflow = true
error_on_unformatted = true
fn_args_density = "Compressed"
enum_discrim_align_threshold = 30
fn_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = false
imports_indent = "Visual"
imports_layout = "Mixed"
merge_imports = true
match_block_trailing_comma = true
max_width = 124
newline_style = "Unix"
reorder_impl_items = true
report_todo = "Unnumbered"
report_fixme = "Unnumbered"
struct_field_align_threshold = 20
use_field_init_shorthand = true
use_try_shorthand = true
format_doc_comments = true
wrap_comments = true
overflow_delimited_expr = true
edition = "2018"
