test:
  cargo +nightly test --features=rand/std
  cargo +nightly test --features=rand/std,use-simd

bench:
  cargo +nightly bench --bench export --features=rand/std -- --nocapture
  cargo +nightly bench --bench render --features=rand/std -- --nocapture
  RUSTFLAGS='-C target-cpu=native' cargo +nightly bench --bench render --features=rand/std -- --nocapture
  cargo +nightly bench --bench render --features=rand/std,use-simd -- --nocapture
  RUSTFLAGS='-C target-cpu=native' cargo +nightly bench --bench render --features=rand/std,use-simd -- --nocapture

clean:
  cargo clean
