(function() {var implementors = {};
implementors["plasma"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PixelRgb.html\" title=\"struct plasma::PixelRgb\">PixelRgb</a>",synthetic:false,types:["plasma::color::PixelRgb"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.RgbIter.html\" title=\"struct plasma::RgbIter\">RgbIter</a>",synthetic:false,types:["plasma::color::RgbIter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.RgbaIter.html\" title=\"struct plasma::RgbaIter\">RgbaIter</a>",synthetic:false,types:["plasma::color::RgbaIter"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PlasmaMixer.html\" title=\"struct plasma::PlasmaMixer\">PlasmaMixer</a>",synthetic:false,types:["plasma::mixers::plasma_default::PlasmaMixer"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PlasmaMixerExp.html\" title=\"struct plasma::PlasmaMixerExp\">PlasmaMixerExp</a>",synthetic:false,types:["plasma::mixers::plasma_experimental::PlasmaMixerExp"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PlasmaMixerFire.html\" title=\"struct plasma::PlasmaMixerFire\">PlasmaMixerFire</a>",synthetic:false,types:["plasma::mixers::plasma_fire::PlasmaMixerFire"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PhaseAmpCfg.html\" title=\"struct plasma::PhaseAmpCfg\">PhaseAmpCfg</a>",synthetic:false,types:["plasma::phase_amp::PhaseAmpCfg"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.PhaseAmp.html\" title=\"struct plasma::PhaseAmp\">PhaseAmp</a>",synthetic:false,types:["plasma::phase_amp::PhaseAmp"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"plasma/struct.Plasma.html\" title=\"struct plasma::Plasma\">Plasma</a>",synthetic:false,types:["plasma::plasma::Plasma"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
