[package]
name = "plasma-web"
version = "0.1.0"
authors = ["Rafał Michalski <royaltm75@gmail.com>"]

license = "GPL-3.0-or-later"

publish = false

readme = "README.md"

[lib]
crate-type = ["cdylib"]
path = "src/rust/lib.rs"

[dependencies]
wasm-bindgen = { version = "0.2", features = ["nightly"] }
js-sys = "0.3"
plasma = { path = "../plasma" }

[dependencies.rand]
version = "0.6.0-pre.1"
# git = "https://github.com/rust-random/rand.git"
# default-features = false
features = ["wasm-bindgen"]

[dependencies.web-sys]
version = "0.3"
features = [
  "ImageData",
  # "CanvasRenderingContext2d",
  "Window",
  "WorkerGlobalScope"
]
